### PR TITLE
draft: migration according to #162

### LINKED ISSUE #162: Migration to Python 3
We try to modernize the terminal

- [x] add formatting
- [x] parallel task: add import for json @phdoerfler 
- [x] drop all irrelevant modules, likely
   - [x] cash payment - @mgmax 
   - [x] flickcharm? (port? find alternative? native?)
   - [x] escpos as module (take in as dependency)
   - [x] naughtystrings? @mgmax 
   - [x] processhelper
   - [x] shopping-backend oerp @patkan 
   - [x] shopping cart from app @mgmax 
   - [x] checkcartafterimport
   - [x] loadfrommobileapp
   - [x] payup manual dialog --> DO NOT remove, needed for testing because FAUcard is not testable without HW
   - [x] statistics dialog
 - [x] migrate to new py3 configparser with https://pypi.org/project/configparser/
 - [x] futurize to stage 2 (`futurize -wn --stage2 .`) (or not, this might produce horrible code, might have to do it manually) --> no longer needed???
 - [x] create a "software emulator" for FAUCard magpos terminal?
 - [x] update FAUCard stuff
 - [ ] find out why every provisioning a new locale is generated :grin: 
 - [x] module by module: import future and make py2/3 compatible
 - [x] drop python2 support
 - [ ] update to most recent version of python-escpos (and configure for our printer)
 - [ ] bonus: simplify code with native py3 syntax (f-strings etc.)
 - [x] install python3 pip into the VM
 - [x] update to newest black style (once we are on py3)
 - [ ] check documentary build with GitHub action
- [x] migrate pyqt to something more modern
  - [x] clarify: what is "more modern", what is the issue?
- [x] get rid of all "python2.7" references (exception: importProdukteOERP.py)
- [x] fix kassenbuch.py
- [x] manually test (and possibly fix) standalone scripts
  - [x]  logWatchAndCleanup
  - [x]  dummy-printserver
  - [x] exportConsumptionMoney
- [ ] fix and improve tests
  - [x] add one basic unittest for calling kassenbuch.py via shell (tests for the python API are already in test_kassenbuch.py, but there are none for the shell command)
  - [x] fix run_unittests, ensure it actually runs the tests
  - [ ] add basic unittests for other standalone scripts
  - [x] setup github action
- [ ] cleanup documentation, README, etc
- [x] remove all Py2 dependencies from install_debian.sh once importProdukteOERP is gone
- [x] then bump Vagrantfile to newest Debian stable
- [x] package black (e.g. shell script that sets up virtualenv and blackens everything, or automated with tox)

### PR DESCRIPTION
**Pull request by patkan**
closes #162

### CODE REVIEW

**Comment by mgmax** [comment]
@patkan I need some help / explanation how to run black (which version, which config, etc)

**Comment by patkan** [comment]
> @patkan I need some help / explanation how to run black (which version, which config, etc)

Hi @mgmax could you resolve it? Any black from this year should be good (they have switched to yearly compatibility in the output). Config: no config :-) black does just the right thing :wink: Does that help?

**Comment by mgmax** [comment]
> Hi @mgmax could you resolve it? Any black from this year should be good (they have switched to yearly compatibility in the output). Config: no config :-) black does just the right thing wink Does that help?

Thanks! We should document this somewhere, and ideally provide some "containerized" method (docker-compose, virtualenv, whatever) that doesn't conflict with other black versions on the system.

**Comment by patkan** [comment]
> > Hi @mgmax could you resolve it? Any black from this year should be good (they have switched to yearly compatibility in the output). Config: no config :-) black does just the right thing wink Does that help?
> 
> Thanks! We should document this somewhere, and ideally provide some "containerized" method (docker-compose, virtualenv, whatever) that doesn't conflict with other black versions on the system.

Agreed.
I think somewhen in the past I have tried to set up a VS Code instance that connects into the vagrant machine, but then you have the issue that your code is also in there. Also you are locked into VS Code (and I think you don't use it, do you?)

I will see what I can do.

**Comment by patkan** [comment]
> > Hi @mgmax could you resolve it? Any black from this year should be good (they have switched to yearly compatibility in the output). Config: no config :-) black does just the right thing wink Does that help?
> 
> Thanks! We should document this somewhere, and ideally provide some "containerized" method (docker-compose, virtualenv, whatever) that doesn't conflict with other black versions on the system.

You can now call ./container_black.sh for a dockerized black. It is configured to exactly the same version as in the github workflow and also configured as the default formatter in vs code.

**Comment by mgmax** [comment]
I will merge whatever is in here on the weekend (or so). Development can then continue in the main branch (called `development` for whatever reason).

Any opinions on squash-merge vs regular merge?

**Pull request merged**
