### PR TITLE
IMPROVE app checkout with better cart view

### LINKED ISSUE #72: App-Import: improve cart viewer
Currently the cart is shown in a dialog box. This does not scale well for large carts.

Maybe refactor the cart view of the main-GUI to be more versatile and use this as viewer in the App-Import-dialog.

### PR DESCRIPTION
**Pull request by patkan**
closes #72

### CODE REVIEW

**Comment by mgmax** [comment]
code duplication is not so good, maybe at least put the common code into a one file and use it from both the gui and the checkout view?

**Comment by patkan** [comment]
Hmm, you are right. I originally thought of making something like a widget with this code associated.
However, my Qt-fu is not that good :-)
Do you have any ideas how to do this really good? Otherwise I would try to move the code together into one space where possible.

**Comment by mgmax** [comment]
hm, subclassing the widget that we use for the table view and putting an updateCartView(order_lines) method there is certainly not wrong.

The subclassed widget can be used in QtDesigner by right-click, set as placeholder for userdefined class. See the search box in the main GUI for an example.

**Comment by patkan** [comment]
@fau-fablab/kasse please review. Should I split the commit into more commits?

**Comment by mgmax** [comment]
Looks good, although I think pylint could complain about a missing newline at the end of GUIHelper.
MyQTableView is not a very self-explaining name, how about CartTableView? 
I think one commit is okay.

**Comment by patkan** [comment]
OK, thank you for reviewing.
I corrected the issues you adressed and will merge now.

**Pull request merged**
