### PR TITLE
Argparse for kassenbuch.py

### PR DESCRIPTION
**Pull request by sedrubal**
- See #76 (but using argcomplete insteat of docopt tab completion)
- Makes #103 easily solveable :tm: 
- May help for #106 as argparse parses the args in utf8(?)
- Introduces tab completion in `kassenbuch.py`
- One could use this in `cash`, too (see #104 )
- Needs testing, but I found no bugs :tm: 
- Some other code improvements :tm: 

Sorry, this is much code but it is very, very mighty :)

_Remember to run [`activate-global-python-argcomplete`](https://pypi.python.org/pypi/argcomplete) to enable tab completion. (also for deploying on kassenterminal)_

### CODE REVIEW

**Comment by mgmax** [comment]
If any argument syntax changed, we also have to update all documentation and cronjobs referring to Kassenbuch.

**Comment by sedrubal** [comment]
I rebuild the old structure and only changed

``` sh
./kassenbuch.py client summary <client>
```

to

``` sh
./kassenbuch.py client show --detail <client>
```

because of the redundancy and I made client names equal to their ids...

I didn't find any docu for that...

**Comment by mgmax** [comment]
I don't understand the comment at "pass # NQA"

**Comment by sedrubal** [comment]
I wanted to mark this 2 lines as ok, because QuantifiedCode complains them, but I think this is ok. I read `#NQA` somewhere but I don't know what this means...

**Comment by mgmax** [comment]
well, if even you don't know what it means then it definitely needs an 
explaining comment

**Comment by sedrubal** [comment]
Here  you are. But I don't understand, why quantified code don't like this... I thought this is pythonic...

**Comment by mgmax** [comment]
Well, usually it would be a bad thing to just ignore import errors, so the warning is generally okay. Here we can safely ignore the warning.

**Comment by sedrubal** [comment]
Ok.

Patrick thinks, one cannot disable single lines for checking...

So is this ready-to-merge?

**Comment by sedrubal** [comment]
I think, this one can be merged. Any concerns?

**Pull request merged**
